# Theme settings
remote_theme: just-the-docs/just-the-docs
title: WorldLM AI Docs
description: Documentation for WorldLM AI services
color_scheme: worldlm

# Enable search with custom styling
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true

# Typography
heading_font: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif
body_font: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif"
mono_font: "'SF Mono', 'Consolas', 'Liberation Mono', monospace"

# External Navigation Links
aux_links:
  "WorldLM Website":
    - "https://worldlm.me"
  "API Console":
    - "https://api.pplm.ai"
aux_links_new_tab: true

# Navigation Structure
nav:
  - title: Getting Started
    children:
      - title: Introduction
        url: /
      - title: Quick Start Guide
        url: /quick-start
      - title: API Keys
        url: /api-keys

  - title: Installation Guides
    children:
      - title: Windows Installation
        url: /docs/en/windows_installation
      - title: macOS Installation
        url: /docs/en/macos_installation
      - title: Android Installation
        url: /docs/en/android_installation

  - title: API Reference
    children:
      - title: Overview
        url: /api/overview
      - title: Authentication
        url: /api/authentication
      - title: Models
        url: /api/models
      - title: Endpoints
        url: /api/endpoints

  - title: Tutorials
    children:
      - title: Basic Usage
        url: /tutorials/basic
      - title: Advanced Features
        url: /tutorials/advanced
      - title: Best Practices
        url: /tutorials/best-practices

  - title: Support
    children:
      - title: FAQ
        url: /support/faq
      - title: Troubleshooting
        url: /support/troubleshooting
      - title: Contact
        url: /support/contact

# Callouts
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green

# Footer content
footer_content: "Copyright &copy; 2024 WorldLM AI. Distributed under the MIT license."

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Enable copy code button
enable_copy_code_button: true

# Google Analytics
ga_tracking: UA-XXXXXXXX-X
ga_tracking_anonymize_ip: true

# Compress HTML in production
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false