data_fetching:
  description: >
    获取指定交易对 {symbol} 和时间间隔 {interval} 的历史交易数据。
  expected_output: >
    包含历史交易数据的 DataFrame。

indicator_calculation:
  description: >
    从 {symbol} 在 {interval} 的历史数据中计算技术指标。
  expected_output: >
    包含历史数据和计算的技术指标的 DataFrame。

market_analysis:
  description: >
    使用技术指标对 {symbol} 在 {interval} 的市场进行分析。
  expected_output: >
    基于技术指标的全面市场分析报告。